version: '3'
services:
  database:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: digisched
      MYSQL_ROOT_PASSWORD: allahuakbar1213
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db_data:/usr/data
    ports:
      - 3306:3306
  app:
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
      args:
        uid: 1000
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    restart: always
    volumes:
      - ./public:/var/www/html/public
      - ./apache_log:/var/log/apache2
    ports:
      - 8888:80
    depends_on:
      - database
    links:
      - database
volumes:
  db_data:
